config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'blog/home#index'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :dashboard, only:[:index]
    resources :posts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admins, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admin_profiles, only: [:edit, :update]
    get 'dashboard', to: 'dashboard#index'
  end
  
  namespace :blog do
    get 'home', to:'home#index'
    get 'search_date', to:'search#by_date'
  end
  
end

app/controllers/blog/home_controller.rb
class Blog::HomeController < BlogController
  def index
    @posts = Post.all
    @categories = Category.all
    @admin = Admin.first
  end
end

app/controllers/blog/search_controller.rb
class Blog::SearchController < BlogController
  
  def by_date
    date = params[:date].to_datetime
    @posts = Post.where(created_at: date.all_day)
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  layout 'blog'
end

app/views/blog/shared/_header.html.erb
<!-- ****** Top Header Area Start ****** -->
<div class="top_header_area">
    <div class="container">
        <div class="row">
            <div class="col-5 col-sm-6">
                <!--  Top Social bar start -->
                <div class="top_social_bar">
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ****** Top Header Area End ****** -->

<!-- ****** Header Area Start ****** -->
<header class="header_area">
    <div class="container">
        <div class="row">
            <!-- Logo Area Start -->
            <div class="col-12">
                <div class="logo_area text-center">
                    <a href="index.html" class="yummy-logo">NutriLife</a>
                    <p>Bem-vindo ao Mundo Saudável</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#yummyfood-nav" aria-controls="yummyfood-nav" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars" aria-hidden="true"></i> Menu</button>
                    <!-- Menu Area Start -->
                    <div class="collapse navbar-collapse justify-content-center" id="yummyfood-nav">
                        <ul class="navbar-nav" id="yummy-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="archive.html">Archive</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="contact.html">Contact</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- ****** Header Area End ****** -->

app/views/blog/shared/_single_post_medium_newest.html.erb
<!-- Single Post MEDIUM NEWEST -->
<% @posts.each do |post| %>
  <div class="col-12 col-md-6">
      <div class="single-post wow fadeInUp" data-wow-delay=".4s">
          <!-- Post Thumb -->
          <div class="post-thumb">
              <%= image_tag(post.images.first.url) %>
          </div>
          <!-- Post Content -->
          <div class="post-content">
              <div class="post-meta d-flex">
                  <div class="post-author-date-area d-flex">
                      <!-- Post Author -->
                      <div class="post-author">
                          <%= link_to "By #{post.admin.admin_profile.name}", '#'  %>
                      </div>
                      <!-- Post Date -->
                      <div class="post-date">
                          <%= link_to post.created_at.strftime("%B %d, %Y"), blog_search_date_path(date: post.created_at) %>
                      </div>
                  </div>
                  <!-- Post Comment & Share Area -->
                  <div class="post-comment-share-area d-flex">
                      <!-- Post Favourite -->
                      <div class="post-favourite">
                          <a href="#"><i class="fa fa-heart-o" aria-hidden="true"></i> 10</a>
                      </div>
                      <!-- Post Comments -->
                      <div class="post-comments">
                          <a href="#"><i class="fa fa-comment-o" aria-hidden="true"></i> 12</a>
                      </div>
                      <!-- Post Share -->
                      <div class="post-share">
                          <a href="#"><i class="fa fa-share-alt" aria-hidden="true"></i></a>
                      </div>
                  </div>
              </div>
              <a href="#">
                  <h3 class="post-headline"><%= post.title %></h3>
              </a>
              <p><%= truncate(post.body, length: 100) %></p>
          </div>
      </div>
  </div>
<% end %>