config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'blog/home#index'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :dashboard, only:[:index]
    resources :posts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admins, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admin_profiles, only: [:edit, :update]
    get 'dashboard', to: 'dashboard#index'
  end
  
  namespace :blog do
    get 'home', to:'home#index'
    get 'search_date', to:'search#by_date'
  end
  
end

app/views/layouts/backoffice_shared/_navbar.html.erb
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html">Administração Nutrilife</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <%= "Olá, #{current_admin.admin_profile.name}" %> <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                        <%= link_to raw("<i class='fa fa-sign-out fa-fw'></i> #{t('Logout')}"), destroy_admin_session_path, method: :delete  %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            
            
            <!-- navbar-side-links -->
            
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav nav-primary-level" id="side-menu">
                        <li>
                            <%= link_to backoffice_dashboard_index_path do %>
                              <i class="fa fa-dashboard fa-fw"></i>
                              <%= t('dashboard') %>
                            <% end %>
                        </li>
                
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Blog <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to 'Novo Post', new_backoffice_post_path %>
                                </li>
                                <li>
                                    <%= link_to 'Visualizar Posts', backoffice_posts_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> <%= t('category') %> <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to t('new_category'), new_backoffice_category_path %>
                                </li>
                                <li>
                                    <%= link_to t('see_categories'), backoffice_categories_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        
                        <li>
                            <%= link_to backoffice_admins_path do %>
                                <i class="fa fa-sitemap fa-fw"></i>
                                <%= t('administrators') %>
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>