config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'blog/home#index'
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :dashboard, only:[:index]
    resources :posts, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admins, only:[:index, :new, :create, :edit, :update, :destroy]
    resources :admin_profiles, only: [:edit, :update]
    get 'dashboard', to: 'dashboard#index'
  end
  
  namespace :blog do
    get 'home', to:'home#index'
    get 'search_date', to:'search#by_date'
  end
  
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  
  def index
    @admins = Admin.all
    @current_admin = current_admin
  end
  
  def new
    @admin = Admin.new
    @admin.build_admin_profile
    authorize @admin 
  end
  
  def create
    @admin = Admin.new(admin_params)
    @admin.role = 1
    if @admin.save
      redirect_to  backoffice_admins_path,
                  notice: t('messages.admin_succesfully_created',
                            item_name: @admin.admin_profile.name)
    else
      helpers.message_notices(@admin)
      render :new
    end
  end
  
  def edit
    authorize @admin
  end
  
  def update
    if @admin.update(admin_params)
      redirect_to  backoffice_admins_path,
                  notice: t('messages.admin_succesfully_edited',
                  item_name: @admin.admin_profile.name)
    else
      helpers.message_notices(@admin)
      render :edit
    end
  end
  
  def destroy
    authorize @admin
    if @admin.destroy
      redirect_to  backoffice_admins_path,
                  notice: t('messages.admin_succesfully_destroyed',
                  item_name: @admin.admin_profile.name)
    else
      helpers.message_notices(@admin)
      redirect_to  backoffice_admins_path
    end
  end
  
  private
  
  def admin_params
    if password_blank?
      params[:admin].extract! :password, :password_confirmation
    end
    if avatar_blank?
      params[:admin].extract! admin_profile_attributes:[:avatar]
    end
    params.require(:admin).permit(:email, :password, :password_confirmation,
                                  admin_profile_attributes:[:name,
                                                            :description,
                                                            :avatar])

  end
  
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def password_blank?
    params[:admin][:password].blank? &&
    params[:admin][:password_confirmation].blank?
  end

  def avatar_blank?
    params[:admin][:avatar].blank?
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:destroy, :edit, :update]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    @category.admin = current_admin
    if @category.save
      redirect_to  backoffice_categories_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @category.update(category_params)
      redirect_to  backoffice_categories_path, notice: 'Categoria editada com sucesso!'
    else
      helpers.message_notices(@category)
      render :edit
    end
  end
  
  def destroy
    if @category.destroy
      redirect_to  backoffice_categories_path, notice: 'Categoria excluída com sucesso!'
    else
      redirect_to  backoffice_categories_path, alert: 'Não foi possível realizar esta ação.'
    end
  end
  
  
  private
  
  def category_params
    params.require(:category).permit(:description, :avatar)
  end
  
  def set_category
    @category = Category.find params[:id]
  end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
    @audits = CustomAudit.all
  end
end

app/controllers/backoffice/posts_controller.rb
class Backoffice::PostsController < BackofficeController
  before_action :set_categories, only:[:new, :edit]
  before_action :set_post, only:[:edit, :update, :destroy]
  

  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.admin = current_admin
    
    if @post.save
      redirect_to  backoffice_posts_path
    else
      helpers.message_notices(@post)
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to  backoffice_posts_path, notice: 'Postagem editada com sucesso!'
    else
      helpers.message_notices(@post)
      render :edit
    end
  end
  
  def destroy
    if @post.destroy
      redirect_to  backoffice_posts_path, notice: 'Postagem excluída com sucesso!'
    else
      redirect_to  backoffice_posts_path, notice: 'Não foi possível realizar esta ação.'
    end
  end
  
  private
  
  def set_post
    @post = Post.find params[:id]
  end
  
  def set_categories
    @categories = Category.all
  end
  
  def post_params
    params.require(:post).permit(:title, :body, :category_id, { images: [] })
  end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'backoffice'

  protected

  def pundit_user
    current_admin
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  def confirm_submit(field, text, options = {})
      options = options[:options]
      field.submit text,
      class: 'btn',
      data:{
        confirm: t('confirmations.edit.body'),
        'confirm-fade': true,
        'confirm-cancel': t('confirmations.cancel'),
        'confirm-cancel-class': t('btn-default'),
        'confirm-proceed': t('confirmations.proceed'),
        'confirm-proceed-class': 'btn-warning',
        'confirm-title': t('confirmations.edit.admin_title', item_name: options[:title])
      }
  end
end

app/helpers/backoffice/backoffice_helper.rb
module Backoffice::BackofficeHelper
  #"{:options=>{:title=>"Morgana Ouriquess", :class=>"btn btn-danger btn-circle"}}"
  #{:options=>{:title=>"Vinicius Godinho Jr.", :class=>"btn btn-danger btn-circle"}}
  def confirm_link_to(text, path, options = {})
    options = options[:options]
    link_to path,
      method: :delete,
      class: options.fetch(:class, 'btn'),
      data:{
        'confirm': options.fetch(:confirm, t('confirmations.destroy.body')),
        'confirm-fade': true,
        'confirm-cancel': options.fetch(:confirm_cancel,
                                        t('confirmations.cancel')),
        'confirm-cancel-class': options.fetch(:confirm_cancel_class,
                                              t('btn-default')),
        'confirm-proceed': options.fetch(:confirm_proceed,
                                         t('confirmations.proceed')),
        'confirm-proceed-class': options.fetch(:confirm_proceed_class,
                                               'btn-danger'),
        'confirm-title': t('confirmations'\
                            ".#{options.fetch(:confirm_title, 'destroy')}"\
                            ".#{controller_name.singularize.downcase}_title",
                            item_name: options.fetch(:title, ''))
      } do
        raw text
    end
  end
  def message_notices(noticer)
      noticer.errors.full_messages.each do |message| 
        if flash[:notice].nil?
          flash[:notice] = [message]
        else
          flash[:notice] << message
        end
      end
  end

end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
  def item_name(audit)
    case audit.auditable_type
      when 'Post' then audit.audited_changes['title']
      when 'Admin', 'AdminProfile'
        value = AdminProfile.find(audit.auditable_id).name
      when 'Category' then audit.audited_changes['description']
      else
        audit.auditable_type
    end
  end
end

app/views/backoffice/admins/edit.html.erb
<%= form_for [:backoffice, @admin], url: {action: 'update'} do |f| %>

  <%= f.fields_for :admin_profile do |profile| %>
    <div>
      <%= profile.label :name %>
      <%= profile.text_field :name %>
    </div>
    
    <div>
      <%= profile.label :description %>
      <%= profile.text_field :description %>
    </div>
  <% end %>
  
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <%= f.fields_for :admin_profile do |profile| %>
    <div>
      <%= profile.label :avatar %>
      <%= profile.file_field :avatar, class: 'btn' %>
    </div>
  <% end %>
  
  <div>
    <%= confirm_submit f, t('edit'), options:{title: @admin.admin_profile.name} %>
  </div>
  
<% end %>

app/views/backoffice/admins/index.html.erb
<h1 class='page-header'>Administradores</h1>
<div class="panel panel-default">
    <div class="panel-heading">
        Listando Administradores
        
        <% if policy(@current_admin).new? %>
          <%= link_to new_backoffice_admin_path,
                      class: 'btn btn-success btn-circle pull-right',
                      style:'margin-top: -5px' do %>
              <i class='fa fa-plus'></i>
          <% end %>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><%= t('name') %></th>
                        <th><%= t('email') %></th>
                        <th><%= t('authorization') %></th>
                        <th style="width:9%"></th>
                    </tr>
                </thead>
                <tbody>
                  <% @admins.each do |admin| %>
                    <tr>
                        <td><%= admin.id %></td>
                        <td><%= admin.admin_profile.name %></td>
                        <td><%= admin.email %></td>
                        <td><%= t(admin.role) %></td>
                        <td>
                          <%= link_to edit_backoffice_admin_path(admin),
                                      class: 'btn btn-warning btn-circle' do %>
                              <i class='fa fa-edit'></i>
                          <% end %>
                          
                          <%= confirm_link_to "<i class='fa fa-edit'></i>",
                                backoffice_admin_path(admin),
                                options: {title: admin.admin_profile.name,
                                         class: 'btn btn-danger btn-circle'} %>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/admins/new.html.erb
<%= form_for [:backoffice, @admin], url: {action: 'create'} do |f| %>

  <%= f.fields_for :admin_profile do |profile| %>
    <div>
      <%= profile.label :name %>
      <%= profile.text_field :name %>
    </div>
    
    <div>
      <%= profile.label :description %>
      <%= profile.text_field :description %>
    </div>
  <% end %>
  
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  
  <%= f.fields_for :admin_profile do |profile| %>
    <div>
      <%= profile.label :avatar %>
      <%= profile.file_field :avatar %>
    </div>
  <% end %>
  
  <div>
    <%= f.submit t('create') %>
  </div>
  
<% end %>